import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// 该文件在 Node.js 环境下运行 - 请勿使用客户端代码(浏览器 API、JSX 等)

/**
 * 创建侧边栏可以让你:
 *  - 对文档进行有序分组
 *  - 为该分组中的每篇文档渲染一个侧边栏
 *  - 提供上一页 / 下一页导航
 *
 * 侧边栏既可以由文件系统自动生成,也可以在此处显式声明。
 *
 * 按需创建任意数量的侧边栏即可。
 */
const sidebars: SidebarsConfig = {
    // 默认情况下,Docusaurus 会根据 docs 目录结构自动生成侧边栏
    tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

    // 也可以手动定义侧边栏
    /*
    tutorialSidebar: [
      'intro',
      'hello',
      {
        type: 'category',
        label: 'Tutorial',
        items: ['tutorial-basics/create-a-document'],
      },
    ],
     */
};

export default sidebars;
