import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsTech: SidebarsConfig = {
    techSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebarsTech;
