import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsRequirements: SidebarsConfig = {
    requirementsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebarsRequirements;
